---
# tasks file for pyenv

  - name: Create pip conf dir
    file:
      path: "{{ansible_env.HOME}}/.pip"
      state: directory

  - name: Deploy pip config
    template:
      src: "pip_conf.j2"
      dest: "{{ansible_env.HOME}}/.pip/pip.conf"
